package.json, src/app/components/register.jsx, src/setupProxy.js
1. 터미널에서 미들웨어 설치 npm install http-proxy-middleware --save
2. 터미널에서 Axios 설치 npm install axios --save
등록 코드는 예시야 추후 수정해도 문제 없음
#참고사이트
https://velog.io/@ung6860/React-Spring-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%83%9D%EC%84%B1
https://velog.io/@yevini118/SpringBoot-CORS-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
=> feat: 백엔드 연동

src/app/components/login.jsx
=> feat: 로그인 기능 구현

src/app/components/Search.jsx
Search.jsx 사용자지정 저장, 연관검색어 우선할당, 사용자지정 검색어 삭제 추가
서버연동 추가
=> feat: Search.jsx 사용자지정 저장 및 관련 핸들러 추가

src/app/components/Search.jsx
http://localhost:3000/search 접속 할 때마다 Diet가 register되는 문제 사용자 지정 추가 시 저장되는 수치가 뻥튀기되는 문제 해결
=> 사용자 지정 추가 기능에서 먹은 양 스크롤바 조정할 때 값이 소수점 0.00000001 와 같이 표현되는 문제

src/app/components/App.jsx, src/app/components/InbodyOcr.css, src/app/components/Log.jsx, src/app/components/Search.jsx, src/app/components/header.jsx, src/app/components/inbodyOcr.jsx
=> Fix: search, log 일부 변경

src/app/components/Log.jsx, src/app/components/Search.jsx, src/index.js
feat: 오늘의 결과 daily-intake, daily-diet-feedback 연동
fix: index.js의 strictMode로 인한 useEffect() 2회호출 현상 해결
=> feat: #23, fix: Search.jsx

src/app/components/Log.css, src/app/components/Log.jsx
=> feat: 오늘의 결과 컴포넌트 인바디 피드백 생성, 인바디 정보 조회 추가

src/app/components/App.jsx, src/app/components/Calender.jsx, src/app/components/DietRecord.jsx
=> feat: 식단 조회 기능 구현

src/app/components/App.jsx, src/app/components/InbodyOcr.css, src/app/components/inbodyOcr.jsx
fix/#22 -> main
- 및 UI 대폭 변경 ✅
- 수기 입력 창 개선 ✅
- 수기 입력 후 저장시 PUT 호출되어 업데이트 구현 의도 ❌
=> fix: InbodyOcr 분석 항목 변경

src/app/components/App.css, src/app/components/Search.jsx
range input 값이 7 자리를 넘으면 줄 바꿈이 일어나는 현상 해결
=> fix: Search 팝업 이슈 수정

src/app/components/App.css, src/app/components/Setting.css, src/app/components/Setting.jsx
=> feat: setting에 알러지 입력 추가

src/app/components/App.css, src/app/components/InbodyOcr.css, src/app/components/Log.css, src/app/components/inbodyOcr.jsx
inbody ocr에서 다른 css 참조한거 주석 처리 함 확인 필요
app.css
=> 인바디ocr ui 수정

src/app/components/Setting.jsx, src/app/components/register.css, src/app/components/register.jsx
색상 개선, setting과 같이 운동 정보 설정할 수 있게 함
=> register ui 개선, 운동 정보 연동

src/app/components/header.css
=> fix: f-log로고 잘림현상

src/app/components/App.css, src/app/components/Setting.css, src/app/components/Setting.jsx, src/app/components/header.jsx
사용자가 로그인이 안된 상태에서도 헤더를 통해 페이지를 이동할 수 있던 현상을 방지
+) Setting.jsx 버튼 디자인과 텍스트 수정
=> feat: 로그인 관리

src/app/components/HomeDetails.jsx, src/app/components/Search.jsx
비정상적인 방식으로 삭제되던 DietRecords에 대한 수정
=> fix: Search.jsx, HomeDetails.jsx 삭제 에러 수정

src/app/components/Calender.jsx, src/app/components/HomeDetails.jsx, src/app/components/Log.jsx, src/app/components/Setting.jsx
사용자 기초대사량, 운동빈도, 운동목표에 따른 신진대사량 계산 및 그래프에 반영 (없을 시 기본값 5000 혹은 500)
=> feat: 신진대사량 반영

package-lock.json, package.json, src/app/components/App.css, src/app/components/App.jsx, src/app/components/Graph.jsx, src/app/components/header.jsx
=> feat: 인바디 그래프 구현

src/app/components/HomeDetails.jsx
아침/점심/저녁/간식 식단 별 음식사진 추가기능 추가
(로컬스토리지를 사용하여 음식URL을 업로드)
=> feat: HomeDetails 컴포넌트 식단 사진 추가기능 구현

src/app/components/HomeDetails.jsx
api요구사항에 적합한 요청 수정, 서버와의 s3Url매개변수를 통한 ImageUrl 동기화
=> fix: HomeDetail 컴포넌트 사진 업로드 api 최신화

src/app/components/Graph.jsx, src/app/components/HomeDetails.jsx
그래프 추가
+) HomeDetails 컴포넌트 마이너 버그 수정
=> feat: 인바디 그래프 컴포넌트 최근변화 추이 그래프 추가
